version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: material-selection-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: material-selection
    volumes:
      - mongodb_data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - material-selection-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: material-selection-elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - material-selection-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: material-selection-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/material-selection?authSource=admin
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - material-selection-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: material-selection-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - material-selection-network

volumes:
  mongodb_data:
  elasticsearch_data:

networks:
  material-selection-network:
    driver: bridge